//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomLink) DeepCopyInto(out *CustomLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomLink.
func (in *CustomLink) DeepCopy() *CustomLink {
	if in == nil {
		return nil
	}
	out := new(CustomLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardAppGroup) DeepCopyInto(out *DashboardAppGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardAppGroup.
func (in *DashboardAppGroup) DeepCopy() *DashboardAppGroup {
	if in == nil {
		return nil
	}
	out := new(DashboardAppGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardAppGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardAppGroupList) DeepCopyInto(out *DashboardAppGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DashboardAppGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardAppGroupList.
func (in *DashboardAppGroupList) DeepCopy() *DashboardAppGroupList {
	if in == nil {
		return nil
	}
	out := new(DashboardAppGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardAppGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardAppGroupSpec) DeepCopyInto(out *DashboardAppGroupSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.CustomLinks != nil {
		in, out := &in.CustomLinks, &out.CustomLinks
		*out = make([]CustomLink, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardAppGroupSpec.
func (in *DashboardAppGroupSpec) DeepCopy() *DashboardAppGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardAppGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardAppGroupStatus) DeepCopyInto(out *DashboardAppGroupStatus) {
	*out = *in
	if in.MatchedDeployments != nil {
		in, out := &in.MatchedDeployments, &out.MatchedDeployments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardAppGroupStatus.
func (in *DashboardAppGroupStatus) DeepCopy() *DashboardAppGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardAppGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSelector) DeepCopyInto(out *DeploymentSelector) {
	*out = *in
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSelector.
func (in *DeploymentSelector) DeepCopy() *DeploymentSelector {
	if in == nil {
		return nil
	}
	out := new(DeploymentSelector)
	in.DeepCopyInto(out)
	return out
}

// Made with Bob
