apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: yamlwrangler-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: docker.io/fumbles/yamlwrangler-operator-catalog:v1.0.6
  displayName: Yamlwrangler Operators
  publisher: Yamlwrangler
  updateStrategy:
    registryPoll:
      interval: 10m

# Made with Bob
